### ISSUE TITLE
How long does it take to denoise CIFAR10 images?

### ISSUE THREAD

**Issue by Xiuyu-Li** [microsoft/PixelDefend#2]
When I run `denoising_fast.py` with a batch size of 250 (default batch size), it took me about 60-70 seconds to denoise one batch of CIFAR10 images on a RTX 2080 Ti. I am wondering if this is the normal running time. Can you tell me what the elapsed time in your case is for the batch size of 250?

**Comment by yang-song** [comment]
I think the elapsed time you observed is reasonable. I remembered that it took more than one hour to denoise all CIFAR-10 test images.

**Comment by Xiuyu-Li** [comment]
I see. Thanks!
